/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package saric.ZupanijskaNogometnaLiga.view;

import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import saric.ZupanijskaNogometnaLiga.controller.ObradaMomcad;
import saric.ZupanijskaNogometnaLiga.model.Momcad;
import saric.ZupanijskaNogometnaLiga.utility.ZupanijskaNogometnaLigaException;


/**
 *
 * @author Hrvoje-PC
 */
public class Momcadi extends javax.swing.JFrame {

    private ObradaMomcad obradaMomcad;
    private DecimalFormat format;
    /**
     * Creates new form Smjerovi
     */
    public Momcadi() {
        initComponents();
        obradaMomcad = new ObradaMomcad();
     
        
        ucitajMomcadi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPopisMomcadi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMomcadi = new javax.swing.JList<>();
        lblNaziv = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        lblStadion = new javax.swing.JLabel();
        lblPredstavnikKluba = new javax.swing.JLabel();
        lblFizioterapeut = new javax.swing.JLabel();
        lblTrener = new javax.swing.JLabel();
        txtStadion = new javax.swing.JTextField();
        txtPredstavnikKluba = new javax.swing.JTextField();
        txtTrener = new javax.swing.JTextField();
        txtFizioterapeut = new javax.swing.JTextField();
        btnDodaj = new javax.swing.JButton();
        btnPromjena = new javax.swing.JButton();
        btnBrisanjei = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPopisMomcadi.setText("Popis Momčadi");

        lstMomcadi.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstMomcadiValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstMomcadi);

        lblNaziv.setText("Naziv momčadi");

        lblStadion.setText("Stadion");

        lblPredstavnikKluba.setText("Predstavnik kluba");

        lblFizioterapeut.setText("Fizioterapeut");

        lblTrener.setText("Trener");

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnPromjena.setText("Promjena");
        btnPromjena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjenaActionPerformed(evt);
            }
        });

        btnBrisanjei.setText("Brisanje");
        btnBrisanjei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrisanjeiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblPopisMomcadi))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTrener)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFizioterapeut)
                                .addGap(62, 62, 62))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtStadion, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(32, 32, 32)
                                            .addComponent(lblNaziv))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lblStadion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtTrener, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFizioterapeut, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPredstavnikKluba)
                                    .addComponent(lblPredstavnikKluba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDodaj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPromjena)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBrisanjei)))
                        .addContainerGap(27, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPopisMomcadi)
                    .addComponent(lblNaziv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblStadion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStadion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblPredstavnikKluba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPredstavnikKluba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTrener)
                            .addComponent(lblFizioterapeut))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTrener, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFizioterapeut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDodaj)
                            .addComponent(btnPromjena)
                            .addComponent(btnBrisanjei))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        Momcad s = new Momcad();
      
       if(!kontrola(s)){
           return;
       }
        
        try {
            obradaMomcad.create(s);
        } catch (ZupanijskaNogometnaLigaException e) {
            JOptionPane.showConfirmDialog(null, e.getPoruka());
            return;
        }
        
        ucitajMomcadi();
        
        ocistiPolja();
        
        
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnPromjenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjenaActionPerformed
         Momcad s = lstMomcadi.getSelectedValue();
         
         if(s==null){
            JOptionPane.showConfirmDialog(null, "Prvo odaberite smjer");
        }
        
        
         if(!kontrola(s)){
           return;
       }
        
        try {
            obradaMomcad.update(s);
        } catch (ZupanijskaNogometnaLigaException e) {
            JOptionPane.showConfirmDialog(null, e.getPoruka());
            return;
        }
        
        ucitajMomcadi();
        
        ocistiPolja();
    }//GEN-LAST:event_btnPromjenaActionPerformed

    private void btnBrisanjeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrisanjeiActionPerformed
        Momcad s = lstMomcadi.getSelectedValue();
        
        if(s==null){
            JOptionPane.showConfirmDialog(null, "Prvo odaberite smjer");
        }
        
        if(obradaMomcad.delete(s)){
            ucitajMomcadi();
            ocistiPolja();
        }else{
            JOptionPane.showConfirmDialog(null,"Momčad nije obrisana jer ima igrače");
        }
    }//GEN-LAST:event_btnBrisanjeiActionPerformed

    private void lstMomcadiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstMomcadiValueChanged
     
        if(evt.getValueIsAdjusting()){
            return;
        }
        
        Momcad s = lstMomcadi.getSelectedValue();
        if(s==null){
            return;
        }
        txtNaziv.setText(s.getNaziv());
        txtFizioterapeut.setText(s.getFizioterapeut());
        txtTrener.setText(s.getTrener());
        txtStadion.setText(s.getStadion());
        txtPredstavnikKluba.setText(s.getPredstavnik_kluba());
    }//GEN-LAST:event_lstMomcadiValueChanged
                                          
        
        
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrisanjei;
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnPromjena;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFizioterapeut;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblPopisMomcadi;
    private javax.swing.JLabel lblPredstavnikKluba;
    private javax.swing.JLabel lblStadion;
    private javax.swing.JLabel lblTrener;
    private javax.swing.JList<Momcad> lstMomcadi;
    private javax.swing.JTextField txtFizioterapeut;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtPredstavnikKluba;
    private javax.swing.JTextField txtStadion;
    private javax.swing.JTextField txtTrener;
    // End of variables declaration//GEN-END:variables

    private void ucitajMomcadi() {
        
        
        DefaultListModel<Momcad> m = new DefaultListModel<>();
                
        for(Momcad s : obradaMomcad.read()){
            m.addElement(s);
        }
        lstMomcadi.setModel(m);
    }
    
private void ocistiPolja(){
    txtTrener.setText("");
       txtNaziv.setText("");
       txtStadion.setText("");
       txtPredstavnikKluba.setText("");
       txtFizioterapeut.setText("");
}


private boolean kontrola(Momcad s) {
    s.setNaziv(txtNaziv.getText());
    s.setFizioterapeut(txtFizioterapeut.getText());
    s.setTrener(txtTrener.getText());
    s.setPredstavnik_kluba(txtPredstavnikKluba.getText());
    s.setStadion(txtStadion.getText());
    return true;
    }
    }
    
  
    
    

